import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Layout from '../components/layout'

export default function Home() {
  return (
    <Layout>
      <Head>
      <title>HOME - Desenvolvimento SEMÂNTICO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section>
        <header>
          <h1 className={styles.title}>
            DESENVOLVIMENTO SEMANTICO COM NEXTJS
          </h1>
        </header>
        <article>
          <h2>Elementos</h2>
          <ul>
            <li>Parágrafos com a tag <em lang="en">p</em>.</li>
            <li>Títulos e subtítulos com a tag h (<em lang="en">h1 - h6</em>  é usado na definição dos títulos e subtítulos).</li>
            <li>Abreviaturas com a tag <em lang="en">abbr</em>.</li>
            <li>Listas devem ser definidas dentro da tag <em lang="en">li</em>.</li>
          </ul>
          <h2>Melhores práticas</h2>
          <ol>
            <li>Informar ao navegador as partes apresentada ao usuário. Exemplo: título, subtítulo, paragrafo, etc. Com a tag específica.</li>
            <li>Estruturar significa dividir em blocos. Artigos contém parágrafos, etc.</li>
            <li>Destacar os títulos com css.</li>
            <li>Uso de ênfase para destacar partes do conteúdo (tag <em lang="en">em</em> e <em lang="en">strong</em>).</li>
            <li>Lembre-se que algumas pessoas possuem dificuldade em diferenciar cores.</li>
            
          </ol>
          <h3>Veja a diferença do uso de <em lang="en">em</em> (tag) abaixo nas palavras feliz e triste. E <em lang="en">strong</em> em nervoso.</h3>
          <p>Estou <em>feliz</em> em viajar mas <em>triste</em>  com a condição do meio ambiente. Também fiquei <strong>nervoso</strong> devido aos atrasos na viajem.</p>

          <h3>Uso de details</h3>
          <details>
            <summary>Clique aqui.</summary>
            <ul>
              <li>Editando lista em detail.</li>
              <li>Fim da lista.</li>
            </ul>

          </details>
        </article>
      </section>
    </Layout>
  )
}
